log:
  debug: true

api:
  listen: 127.0.0.1:8099
  debug: true
  secret: admin

upstreams:
  - tag: google-dns
    type: tls
    options:
      address: 8.8.4.4
      servername: dns.google
      idle-timeout: 1m
      query-timeout: 500ms
      dialer:
        timeout: 500ms

  - tag: ali-dns
    type: tls
    options:
      address: 223.5.5.5
      idle-timeout: 1m
      query-timeout: 200ms
      dialer:
        timeout: 200ms

match-plugins:
  - tag: geosite
    type: sing-geosite
    args:
      file: /workdir/cdns/geosite.db
      code:
        - private
        - gfw

exec-plugins:
  - tag: cache
    type: redis-cache
    args:
      address: /var/run/redis/redis.sock
      database: 6

workflows:
  - tag: main
    rules:
      - match_and:
          - plugin:
              tag: geosite
              args:
                code: private
        exec:
          - return: SUCCESS

      - match_and:
          - qtype:
              - 28
              - 65
        exec:
          - return: SUCCESS

      - exec:
          - plugin:
              tag: cache
              args:
                restore: true
                return: true

      - match_and:
          - plugin:
              tag: geosite
              args:
                code:
                 - gfw
        exec:
          - upstream: google-dns
          - plugin:
              tag: cache
              args:
                store: true
                return: true

      - exec:
          - upstream: ali-dns
          - plugin:
              tag: cache
              args:
                store: true
                return: true

listeners:
  - tag: local-udp
    type: udp
    options:
      listen: :1053
    workflow: main

  - tag: local-tcp
    type: tcp
    options:
      listen: :1053
    workflow: main
